### PR TITLE
Added User Variables referencing in content pages

### PR DESCRIPTION
**Pull request by apmuthu**
A new file `site_vars.php` having user reference-able variables in a `$void_config array` and wrapped in double curly braces in content pages is now possible.

Local `images` sub-folder added along with dummy `index.html` pages in sub-folders.

`Parsedown.php` updated to `v1.6.0`

### CODE REVIEW

**Comment by tyeeman** [comment]
Nice update! I think these changes should be merged, especially making it php 5.3 compatible.

**Comment by Andrewpk** [comment]
http://php.net/supported-versions.php

Why do people care so much about 5.3? If your host doesn't support modern and supported PHP you should move hosts. If your extensions aren't being updated than you should evaluate whether you actually need them. There's no excuse to stay on 5.3.

**Comment by tyeeman** [comment]
True. Just came across another cms that wants >=php ver.7.

It's unfortunate that non-coders can't just update a php application on their own, long after the developer has stopped maintaining the code. What a wonderful world it would be if we could just run another application that updates all the files to the current version. I know what your going to say, just learn php. I like using it not coding it.  Your right, I use Lunarpages and they should have updated my shared server long ago. I've never changed servers. Is it seemless to me as a user or will I have to reconfigure settings?

**Comment by apmuthu** [comment]
There is a lot of code out there that works perfectly well with PHP 5.3 and the users / devs have become familiar with that version and see no need to change. Also coding for the lowest common denominator will not leverage the core strengths of the specific version being used. Latest is not always the greatest/best. If it ain't broken, don't fix it.

Newer versions of PHP will possibly become proprietary now that Oracle has the stranglehold.... and it will soon become a strict java clone...

The PHP team can also have what is known as a version compatibility mode setting to enable any version specific code to run on the latest version.

**Comment by josephernest** [comment]
I want to keep the number of features and number of files/folders in the package as low as possible, so I don't include it, but definetely an interesting update for users who want some enhancements.

**Pull request closed without merging**
